### ISSUE TITLE
better_sqlite3.node undefined symbol: ENV_CIPHER_key_lenght

### ISSUE THREAD

**Issue by sbe-arg** [0mniteck/Signal-Desktop-Builder#4]
v5.48 fails to start with error `better_sqlite3.node undefined symbol: ENV_CIPHER_key_lenght`

running latest mobian on pinephone as today july 8th

**Comment by sbe-arg** [comment]
I'm not seeing this problem anymore I think It wasa local missconfig should close the issue.

**Comment by 0mniteck** [comment]
Testing with build 5.56.0 on a fresh install to confirm the bug has been fully resolved.

**Comment by 0mniteck** [comment]
Still seeing the same bug :(

**Comment by 0mniteck** [comment]
Last version that works is 5.45.0

**Comment by 0mniteck** [comment]
Resolved with release of 05.56.0-stable
