### ISSUE TITLE
This does not work on pureOs

### ISSUE THREAD

**Issue by pparent76** [0mniteck/Signal-Desktop-Builder#5]
Hello,

Just to mention it does not work on pureOS / default librem 5 system which is a bit of a pity.

Launching the app fails with an error window saying "Unhandled promised rejection: Error libcrypto.so.3 cannot open shared file, so such file or directory"

I guess it's a problem with debian version.

Thank you so much for the work!

**Comment by 0mniteck** [comment]
I clearly state this is built for mobian bookworm not generally for debian but by changing one line it would easily build for most if not all debian based OSes
